version: "2"
services:
  db: 
    image: mongo
    ports:
      - '27018:27017'
  web:
    links:
      - db
    build: .
    command: java -jar target/CodeQuality-0.0.1-SNAPSHOT.jar
    ports:
      - '8080:8080'
    volumes:
      - .:/code
      - ./dependencies:/root/.m2
